"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-05-27 18:43:49.118038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Standalone PG enum types from db_schema.sql that no column references
    # (health status is computed at runtime; confidence_flags is stored as JSONB).
    # Created for schema fidelity. The other 3 enums are created implicitly by the
    # tables whose columns use them (import_status, scenario_kind, ai_action_type).
    op.execute(
        "CREATE TYPE stock_health_status AS ENUM "
        "('HEALTHY', 'LOW', 'CRITICAL', 'STOCKOUT')"
    )
    op.execute(
        "CREATE TYPE confidence_flag AS ENUM "
        "('RECENT_STOCKOUT', 'LEADING_ZEROS', 'HIGH_VOLATILITY', 'DECLINING_TREND', "
        "'VELOCITY_DIVERGENCE', 'SPARSE_DATA', 'MOQ_OVERSHOOT')"
    )
    op.create_table('app_config',
    sa.Column('id', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('shipping_buffer_days', sa.Integer(), server_default=sa.text('7'), nullable=False),
    sa.Column('forecast_window_days', sa.Integer(), server_default=sa.text('60'), nullable=False),
    sa.Column('growth_pct', sa.Numeric(precision=5, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('critical_multiplier', sa.Numeric(precision=4, scale=2), server_default=sa.text('1'), nullable=False),
    sa.Column('low_multiplier', sa.Numeric(precision=4, scale=2), server_default=sa.text('1.5'), nullable=False),
    sa.Column('velocity_window_short', sa.Integer(), server_default=sa.text('7'), nullable=False),
    sa.Column('velocity_window_long', sa.Integer(), server_default=sa.text('14'), nullable=False),
    sa.Column('volatility_cv_threshold', sa.Numeric(precision=4, scale=2), server_default=sa.text('0.5'), nullable=False),
    sa.Column('velocity_divergence_threshold', sa.Numeric(precision=4, scale=2), server_default=sa.text('0.5'), nullable=False),
    sa.Column('sparse_data_min_days', sa.Integer(), server_default=sa.text('14'), nullable=False),
    sa.Column('moq_overshoot_multiplier', sa.Numeric(precision=4, scale=2), server_default=sa.text('2'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.CheckConstraint("id = 'active'", name='ck_app_config_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('import_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('file_checksum', sa.String(length=64), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('data_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'PARTIAL', 'FAILED', 'SKIPPED', name='import_status'), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('skus_created', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('skus_updated', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('snapshots_created', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('sales_rows_inserted', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('sales_rows_skipped', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_checksum')
    )
    op.create_index('ix_import_runs_started_at', 'import_runs', ['started_at'], unique=False)
    op.create_index('ix_import_runs_status', 'import_runs', ['status'], unique=False)
    op.create_table('saved_scenarios',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.Enum('BASELINE', 'CUSTOM', name='scenario_kind'), server_default=sa.text("'CUSTOM'"), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('shipping_buffer_days', sa.Integer(), nullable=False),
    sa.Column('forecast_window_days', sa.Integer(), nullable=False),
    sa.Column('growth_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('critical_multiplier', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('low_multiplier', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_saved_scenarios_kind', 'saved_scenarios', ['kind'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('production_lead_days', sa.Integer(), nullable=False),
    sa.Column('shipping_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('skus',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sku_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('cost_per_unit_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('retail_price_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('moq', sa.Integer(), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_code')
    )
    op.create_index('ix_skus_category_id', 'skus', ['category_id'], unique=False)
    op.create_index('ix_skus_is_active', 'skus', ['is_active'], unique=False)
    op.create_index('ix_skus_supplier_id', 'skus', ['supplier_id'], unique=False)
    op.create_table('ai_suggestions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('context_hash', sa.String(length=64), nullable=False),
    sa.Column('context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action_type', sa.Enum('ORDER_NOW', 'ORDER_SOON', 'WAIT', 'INVESTIGATE', 'DISCONTINUE', name='ai_action_type'), nullable=False),
    sa.Column('urgency', sa.Integer(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('suggested_po_qty', sa.Integer(), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_id', 'context_hash', name='uq_ai_cache_key')
    )
    op.create_index('idx_sku_history', 'ai_suggestions', ['sku_id', 'generated_at'], unique=False)
    op.create_index('ix_ai_suggestions_context_hash', 'ai_suggestions', ['context_hash'], unique=False)
    op.create_index('ix_ai_suggestions_generated_at', 'ai_suggestions', ['generated_at'], unique=False)
    op.create_index('ix_ai_suggestions_sku_id', 'ai_suggestions', ['sku_id'], unique=False)
    op.create_table('sku_sales_daily',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('units_sold', sa.Integer(), nullable=False),
    sa.Column('import_run_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.id'], initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_id', 'sale_date', name='uq_sku_sale_date')
    )
    op.create_index('idx_sku_sales_lookup', 'sku_sales_daily', ['sku_id', 'sale_date'], unique=False)
    op.create_index('ix_sku_sales_daily_sale_date', 'sku_sales_daily', ['sale_date'], unique=False)
    op.create_index('ix_sku_sales_daily_sku_id', 'sku_sales_daily', ['sku_id'], unique=False)
    op.create_table('sku_snapshots',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('cost_per_unit_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('retail_price_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('moq', sa.Integer(), nullable=False),
    sa.Column('confidence_flags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('import_run_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.id'], initially='IMMEDIATE', deferrable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_id', 'snapshot_date', name='uq_sku_snapshot_date')
    )
    op.create_index('ix_sku_snapshots_import_run_id', 'sku_snapshots', ['import_run_id'], unique=False)
    op.create_index('ix_sku_snapshots_sku_id', 'sku_snapshots', ['sku_id'], unique=False)
    op.create_index('ix_sku_snapshots_snapshot_date', 'sku_snapshots', ['snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sku_snapshots_snapshot_date', table_name='sku_snapshots')
    op.drop_index('ix_sku_snapshots_sku_id', table_name='sku_snapshots')
    op.drop_index('ix_sku_snapshots_import_run_id', table_name='sku_snapshots')
    op.drop_table('sku_snapshots')
    op.drop_index('ix_sku_sales_daily_sku_id', table_name='sku_sales_daily')
    op.drop_index('ix_sku_sales_daily_sale_date', table_name='sku_sales_daily')
    op.drop_index('idx_sku_sales_lookup', table_name='sku_sales_daily')
    op.drop_table('sku_sales_daily')
    op.drop_index('ix_ai_suggestions_sku_id', table_name='ai_suggestions')
    op.drop_index('ix_ai_suggestions_generated_at', table_name='ai_suggestions')
    op.drop_index('ix_ai_suggestions_context_hash', table_name='ai_suggestions')
    op.drop_index('idx_sku_history', table_name='ai_suggestions')
    op.drop_table('ai_suggestions')
    op.drop_index('ix_skus_supplier_id', table_name='skus')
    op.drop_index('ix_skus_is_active', table_name='skus')
    op.drop_index('ix_skus_category_id', table_name='skus')
    op.drop_table('skus')
    op.drop_table('suppliers')
    op.drop_index('ix_saved_scenarios_kind', table_name='saved_scenarios')
    op.drop_table('saved_scenarios')
    op.drop_index('ix_import_runs_status', table_name='import_runs')
    op.drop_index('ix_import_runs_started_at', table_name='import_runs')
    op.drop_table('import_runs')
    op.drop_table('categories')
    op.drop_table('app_config')
    # Drop every PG enum type: autogenerate creates the 3 column-bound enums
    # implicitly via their tables but never tears them down, and the 2 standalone
    # ones are created above. IF EXISTS keeps this idempotent.
    for enum_name in (
        'stock_health_status',
        'confidence_flag',
        'import_status',
        'scenario_kind',
        'ai_action_type',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
    # ### end Alembic commands ###
